### ISSUE TITLE
Switch to immutabable data

### ISSUE THREAD

**Issue by xD3CODER** [combine/universal-react-redux#42]
It could be great to add a library like ImmutableJS on the redux store

**Comment by calvinl** [comment]
Agreed. I’ll add it for the next release. 

I’m currently working on adding code splitting at the moment. Also working on a CLI tool and possibly transitioning to this being a framework in the future.

**Comment by xD3CODER** [comment]
Great project !

**Comment by calvinl** [comment]
@D3VHAX what do you think about adding [redux-immutable-state-invariant](https://github.com/leoasis/redux-immutable-state-invariant) in dev environment only instead? 

I think we should leave adding ImmutableJS to the end user. Adding this would at least spit out an error when using regular objects.

**Comment by xD3CODER** [comment]
I didn't know this module. It's seems to be a great alternative. But the problem is that if we want to implement ImmutableJS for production, components and store have to be refactored.

**Comment by calvinl** [comment]
@D3VHAX That's true, good point. 

One of the philosophies for this boilerplate was to keep it as un-opinionated as possible when it comes to building your app, but be opinionated on the configuration and setup of universal rendering. 

IMO, I think bundling ImmutableJS here would be opinionated on how you build the app. Maybe there's something we could do with making it so that switching to ImmutableJS would be pretty easy/straightforward?

**Comment by xD3CODER** [comment]
@calvinl  Honestly, idk. I'm new in React community

**Comment by calvinl** [comment]
@D3VHAX no worries - I think we will leave Immutable out for now as the focus should be on configuration, IMO. Feel free to open again if you want to discuss further!
