### ISSUE TITLE
Add server-side HMR

### ISSUE THREAD

**Issue by xD3CODER** [combine/universal-react-redux#44]
It could be a great alternative to nodemon

What do you think ?

**Comment by calvinl** [comment]
Sure, I’ll take a look into it. Let me know if you have any suggestions or a PR if you want to look into it.

**Comment by calvinl** [comment]
@D3VHAX I've looked in server HMR and while it looks cool, it doesn't seem to provide that much more advantage over nodemon, other than the fact that you would not need to explicitly add watch files/directories like you do with nodemon.

In light of this, I've [created a PR](https://github.com/combine/universal-react-redux/pull/47) that uses [node-dev](https://github.com/fgnass/node-dev) in place of nodemon. It allows us to not have to specify a watch list since it only reloads only `require()`ed files.

**Comment by calvinl** [comment]
Closing for now, feel free to re-open if you have a better/actual solution for server-side HMR.
