### ISSUE TITLE
Including fonts in base _fonts.scss

### ISSUE THREAD

**Issue by just2jays** [combine/universal-react-redux#49]
I'm unable to use the Google fonts via @import in the `./common/css/base/_fonts.scss` partial.

It seems as if the @import statement is being rendered rather than the contents of the font url request.

For instance, if I clone this repo and simply add another Font import underneath the included "Open Sans" `@import url('https://fonts.googleapis.com/css?family=Roboto');` - I'm unable to reference this Roboto font. 

Am I missing a step here?! Thanks for any help.

**Comment by calvinl** [comment]
@just2jays Good catch! 

It looks like it's a precedence issue in this [line of code here](https://github.com/combine/universal-react-redux/blob/master/client/index.js#L11). Basically, webpack is compiling css modules since `App` is imported before the styles file is.

Try moving the styles import to line `2`, and it should fix the issue.

e.g. 
```
import 'babel-polyfill';
import './styles';
// ...
```
