### ISSUE TITLE
Chromium: the checksum was invalid

### ISSUE THREAD

**Issue by zitsen** [combine/universal-react-redux#6]
I'm a newer in NodeJS. Appreciate for your work and appologize if this is something trouble you.

Following the readme install and start, Chromium console warnings here:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) /a><a style="cursor:pointer;font-weight:
 (server) /a><a style="cursor:text;font-weight:bol
```

Things just work well but I don't know if this warning helpful.

**Comment by calvinl** [comment]
@zitsen I believe that has to do with Redux DevTools rendering slightly differently on the server versus the client. You'll see this message whenever the client-rendered markup differs from the server-generated markup. It's probably safe to ignore since it looks like it's part of DevTools -- you shouldn't see this in production.

**Comment by zitsen** [comment]
Ah, I see, thanks for your explain!
